import { createElement } from '@lwc/engine-dom';
import DH_VerifyChat from 'c/dH_VerifyChat';

describe('c-d-h-verify-chat', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-d-h-verify-chat', {
            is: DH_VerifyChat
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});